# Generated by Django 4.0.6 on 2022-07-08 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tooldatedetails',
            name='tool_date',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='tool.tooldate'),
            preserve_default=False,
        ),
    ]
