# Generated by Django 4.0.6 on 2022-07-09 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0002_tooldatedetails_tool_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tooldate',
            name='id',
        ),
        migrations.RemoveField(
            model_name='tooldatedetails',
            name='id',
        ),
        migrations.AddField(
            model_name='tooldate',
            name='tool_date_id',
            field=models.AutoField(default='1', primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tooldatedetails',
            name='tool_date_details_id',
            field=models.AutoField(default='1', primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
