# Generated by Django 4.0.6 on 2022-07-09 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0003_remove_tooldate_id_remove_tooldatedetails_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tooldatedetails',
            name='tool_date',
        ),
        migrations.AddField(
            model_name='tooldate',
            name='tool_date_details_id',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='tool.tooldatedetails'),
            preserve_default=False,
        ),
    ]
