# Generated by Django 4.0.6 on 2022-07-09 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0004_remove_tooldatedetails_tool_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tooldate',
            name='tool_date_details_id',
        ),
        migrations.AddField(
            model_name='tooldatedetails',
            name='tool_date',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='tool.tooldate'),
            preserve_default=False,
        ),
    ]
