# Generated by Django 4.0.6 on 2022-07-10 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0005_remove_tooldate_tool_date_details_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tooldatedetails',
            name='extra_hours',
            field=models.DecimalField(decimal_places=2, max_digits=2),
        ),
    ]
