# Generated by Django 4.0.6 on 2022-07-10 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0007_alter_tooldatedetails_extra_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tooldatedetails',
            name='extra_hours',
            field=models.FloatField(),
        ),
    ]
