# Generated by Django 4.0.6 on 2022-07-11 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0009_tooldatedetails_time_out'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tooldate',
            old_name='lst_date',
            new_name='lst_extra_hours',
        ),
    ]
